language: python

python:
  - 2.7

matrix:
  include:
    - python: 2.7
      env:
        - TESTS="true"
    - python: 3.7
      dist: xenial
      env:
        - TESTS="true"
    - python: 3.8
      dist: xenial
      env:
        - TESTS="true"
    - python: 3.8
      dist: xenial
      env:
        - LINT="true"
    - python: 3.7
      env:
        - DOCS="true"
        # Doctr deploy key for pyflyby/pyflyby
        - secure: "hLezkTmoSLQIKKll+vzfhqxqIR6fekQrjigNcOYT6iUGElB0xRgCdHcHWvb/VHEDqcsIz7OgicrCiWulwo/qzHgm7Lz+T+cqXtslD84X0z81HwKhn6d1cFdo7G2QWWuzGPCTYEIHqFfGcqpOLxXBr7wfkK1o0tp5WPFhKyfS6IvYvr6CLQXbILyaUnwVTbro+UWkCIXihpVNtVfxwXmdTEo+S4sFqCshza0odPFFnb9y9hnyA+uYpaPJMIUnpXzNUbZkoBk9mE351oXBVvGBaAkohC9YoulbrgasXo+XHAGChFagP5/gHw2Xl2niVbc7EpJdVEe7ouLT6R9nc65MBi0Na5oO2bwQMFoaoIeyGq8R2HXGo48Y3GC5PcqAxCMGSlpkBV8bR6VlhZj2yUh2fXleMhV45i492cjsl+AXyVVxPWE2F0afopHr+S5NbRqN6A3Ld8JwDoQatHXkJKHsxXvfufRFXAgkoHFVLlO0YL7L7uJzMhNCds0/abfjGmqSOB9ihYHsW6roPY7258jjn3sfasDsXjKvmmtTc0IKjX/D/woruP3kpq8417dzhQz/YBFuj8NE6p64fXN1DOJhPEpU5JTZaV0LjtIQvVnuQnau6xlpAH/jk7fO2LWhu+c7/BPXrQhZB2EvQ6XahEtyoIDdn+F+DoI39iZ9JGKnxWQ="

install:
  - set -e
  - pip install -U pip
  # Install prompt-toolkit from git until a release is made with
  # PROMPT_TOOLKIT_NO_CPR environment variable support.
  # Install jupyter_console from
  # https://github.com/jupyter/jupyter_console/pull/187 until it is included
  # in a release.
  # Install ipykernel from master until a version after 5.1.2 is released.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        pip install -U "pexpect>=3.3" pyflakes pytest epydoc rlipython requests jupyter flaky flake8 wheel;
    else
        pip install -U git+https://github.com/asmeurer/jupyter_console@display_completions;
        pip install -U "pexpect>=3.3" pyflakes pytest rlipython requests jupyter flaky flake8 'notebook<6.1' 'prompt_toolkit<3.0.6' wheel;
    fi
  - if [[ "${DOCS}" == "true" ]]; then
        pip install sphinx sphinx_rtd_theme sphinx-autodoc-typehints;
    fi
  - pip list

script:
  # - set -x
  - set -e
  - shopt -s extglob globstar
  - python setup.py sdist bdist_wheel
  # pyflakes all files except for known_imports/*, etc/*, and __init__.py,
  # which are all unused imports. We use flake8 so we can use noqa if
  # necessary.
  - |
    if [[ "${LINT}" == "true" ]]; then
        flake8 --exclude known_imports,etc,__init__.py --select=F;
    fi
  # Test for invalid escape sequences (will be syntax errors in a future
  # Python version)
  - |
    if [[ "${TESTS}" == "true" ]]; then
        python -We:invalid -m compileall -f -q lib/ etc/;
    fi
  - |
    if [[ "${TESTS}" == "true" ]]; then
        export DEBUG_TEST_PYFLYBY=1;
    fi
  - |
    if [[ "${TESTS}" == "true" ]]; then
        pytest --doctest-modules lib tests;
    fi
  # Smoke test tidy-imports on the codebase. This only fails if there is an
  # exception from a bug, but we could also make it fail if there are imports
  # that need to be tidied.
  - |
    if [[ "${TESTS}" == "true" ]]; then
        ./bin/tidy-imports -d lib/python/ tests/;
    fi
  - |
    if [ "${DOCS}" = "true" ]; then
        cd doc;
        make html;
        cd ..;
        pip install doctr;
        doctr deploy .;
    fi
