language: python

sudo: false
python:
  - 2.7

matrix:
  include:
    - python: 2.7
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - set -e
  - pip install -U pip
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        pip install -U "pexpect>=3.3" pyflakes pytest epydoc rlipython requests jupyter flaky flake8;
    else
        pip install -U "pexpect>=3.3" pyflakes pytest rlipython requests jupyter flaky flake8;
    fi
  - pip list

script:
  - set -x
  - shopt -s extglob globstar
  # pyflakes all files except for known_imports/*, etc/*, and __init__.py,
  # which are all unused imports. We use flake8 so we can use noqa if
  # necessary.
  - flake8 --exclude known_imports,etc,__init__.py --select=F
  - export DEBUG_TEST_PYFLYBY=1
  - pytest --doctest-modules lib tests
