language: python

sudo: false
python:
  - 2.7

matrix:
  include:
    - python: 2.7
    - python: 3.7
      dist: xenial
      sudo: true

  allow_failures:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - set -e
  - pip install -U pip
  - pip install -U "pexpect>=3.3" pyflakes pytest epydoc rlipython requests jupyter flaky
  - pip list

script:
  - set -e
  - set -x
  - export DEBUG_TEST_PYFLYBY=1
  - pytest --doctest-modules lib tests
