name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["2.7", "3.7", "3.8", "3.9", "3.10"]
        include:
          - os: macos-latest
            python-version: "3.10"

    env:
      DEBUG_TEST_PYFLYBY: 1

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install and update Python dependencies on Python 2
      if: ${{ matrix.python-version == '2.7'}}
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade "pexpect>=3.3" 'pytest<7' epydoc rlipython requests jupyter flaky wheel 'pytest-cov<3'
        pip install -e .
    - name: Install and update Python dependencies on Python 3
      if: ${{ matrix.python-version != '2.7'}}
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade "pexpect>=3.3" 'pytest<7' rlipython ipykernel==5.4.3 requests jupyter flaky 'notebook<6.1' 'prompt_toolkit<3.0.15' wheel 'jupyter_console>=6.2' 'pytest-cov<3' ipython 'coverage<6.3'
        pip install -e .
    - name: test release build
      run: |
        python setup.py sdist bdist_wheel
    - name: compileall
      run: |
        python -We:invalid -m compileall -f -q lib/ etc/;
    - name: pytest
      run: |
        python -m pytest --cov=pyflyby --cov-report=xml --doctest-modules --maxfail=3 lib tests
    - uses: codecov/codecov-action@v2
    - name: Build docs
      if: ${{ matrix.python-version == '3.10'}}
      run: |
        pip install sphinx sphinx_rtd_theme sphinx-autodoc-typehints
        cd doc
        make html
        cd ..
