name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    env:
      DEBUG_TEST_PYFLYBY: 1

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install and update Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade "pexpect>=3.3" pyflakes pytest rlipython ipykernel==5.4.3 requests jupyter flaky flake8 'notebook<6.1' 'prompt_toolkit<3.0.15' wheel 'jupyter_console>=6.2'
        pip install -e .
    - name: test release build
      run: |
        python setup.py sdist bdist_wheel
    - name: lint
      run: |
        flake8 --exclude known_imports,etc,__init__.py --select=F;
    - name: compileall
      run: |
        python -We:invalid -m compileall -f -q lib/ etc/;
    - name: pytest
      run: |
        python -m pytest --doctest-modules lib tests
    - name: Self-tidy-import
      run: |
        ./bin/tidy-imports -d lib/python/ tests/
        
